name: Car Price Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Her gün 06:00 UTC

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl schedule
    
    - name: Run Price Tracker
      env:
        GMAIL_USER: ${{ secrets.EMAIL_SENDER }}
        GMAIL_APP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python car_price_tracker.py
    
    - name: Upload Excel Report (Artifact)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: price-report-${{ github.run_number }}
        path: '*.xlsx'
        retention-days: 30
    
    - name: Notify on Failure
      if: failure()
      run: |
        echo "❌ Job failed! Check the logs above."
